
icon_alvo = ':dart:'
icon_alerta_sirene = ':rotating_light:'
icon_alerta_sino = ':bell:' 
icon_alerta_mega_fone = ':mega:'
icon_alerta_mega_fone2 = ':loudspeaker:'
icon_salvar = ':floppy_disk:'
icon_fone = ':phone:'
icon_dinheiro = ':dollar:'
icon_dinheiro_voando = ':money_with_wings:'
icon_dinheiro_saco = ':money_with_wings:'
icon_dinheiro_cifrao = ':heavy_dollar_sign:'
icon_chave = ':key:'
icon_tendencia_alta = ':chart_with_upwards_trend:'
icon_tendencia_baixa = ':chart_with_downwards_trend:'
icon_grafico_barras = 'bar_chart'
icon_bandeira_brasil = ':brazil:'
icon_hug = ':hugs:'